### ISSUE TITLE
6.1.1 a été release depuis la branched de debug

### ISSUE THREAD

**Issue by ngodfraind** [UJM-dev/ExoBundle#124]
Et c'est bizarre car il y a des erreurs qui ont été corrigées depuis dessus (par exemple l'édition des propriétés d'un exercice est correcte sur le master, mais pas sur la 6.1.1).

Le commit du fix est ici: https://github.com/UJM-dev/ExoBundle/commit/13a3de97153d40bc8a7a40ae474760ce2cce040b

Du coup la 6.1.1 est un peu foireuse je pense. Il y a 81 commit sur le master d'avance.

**Comment by david42** [comment]
En fait c'est normal car le master contient déjà des modifes du prochain tag 6.2.0.
La 6.1.1 correspond à la 6.1.0 avec le commit qui résout le problème de l'édition des QCM.
On avait pas prévu vraiment prévu de faire de tag entre la 6.1.0 et 6.2.0

**Comment by ngodfraind** [comment]
D'accord.
Il y a une date pour la 6.2.0 ?

**Comment by david42** [comment]
Le tag 6.2.0 devrait arriver la semaine prochaine.
