### ISSUE TITLE
Bug for the Manage Document button

### ISSUE THREAD

**Issue by stmolivier** [UJM-dev/ExoBundle#24]
Tested with Claroline v4.2.2
Logged as Administrator, 
Desktop > Ma banque de questions 
Click on "Manage Documents" (gérer mes documents) button leads to a error 500 
```
Notice: Undefined variable: allowToDel in /home/olivier/www/Claroline/vendor/ujm/exo-bundle/UJM/ExoBundle/Controller/QuestionController.php line 1029
500 Internal Server Error - 
```

**Comment by UJM-dev** [comment]
Hi,

This bug will be solved with the next update.

Thanks for this reply
