### ISSUE TITLE
MISSING : translation for ACTION term in log

### ISSUE THREAD

**Issue by stmolivier** [UJM-dev/ExoBundle#88]
When i'm setting a automatic evaluation in an Activity, if the main ressource is an exercice, i have "log_resource-ujm_exercise-exercise_evaluated_filter" for the action field : there is no translation string for this ("obternir un résultat pour l'exercice" ?)

**Comment by charlotte42** [comment]
Fix error in the next tag

**Comment by stmolivier** [comment]
This is not fixed : in Claro 6.6.4.3 with last version of ExoBundle

![action](https://cloud.githubusercontent.com/assets/8692228/11342846/9568a4d0-9209-11e5-9263-2a50d58c702c.png)
