### ISSUE TITLE
Bug : missing headers for hole management in "text with hole"

### ISSUE THREAD

**Issue by CPASimUSante** [UJM-dev/ExoBundle#93]
![textwithholes](https://cloud.githubusercontent.com/assets/14015697/10868914/f3c37b86-809d-11e5-9cd9-58320c84d5ee.png)

This header are userful, especially for the checkbox

**Comment by marion42** [comment]
For don't overload the page, we haven't add the header of the table. But we have put place-holder and tooltips on this fields. We can add tooltips for all fields.

**Comment by stmolivier** [comment]
OK, i can hear the need to not overload, but yes the tooltip are at least still necessary (for "casual" users : that don't use very often this tool)

**Comment by marion42** [comment]
Ok, we will add tooltip for "Response" and for "Points". (There is already the tooltip for the case.)
