### ISSUE TITLE
Improvement : For association type, put the tables on full width

### ISSUE THREAD

**Issue by CPASimUSante** [UJM-dev/ExoBundle#94]
The text and display is broken if the proposition / label is more than a word.
The Label table should then be underneath the proposition table.
![association](https://cloud.githubusercontent.com/assets/14015697/10870538/8ad46eb6-80cd-11e5-8b2a-dd8f00e47917.png)

**Comment by marion42** [comment]
This bug is fixed. It will appear in the next tag for the 5 version.

**Comment by stmolivier** [comment]
ok, will it be fixed for v6 as well ? (this is the version i use) Thank you

**Comment by marion42** [comment]
Yes it will fixed in the v6 in the week.

**Comment by stmolivier** [comment]
Geat !
